//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更此檔案可能會導致不正確的行為，而且若已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ldapService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.direk.com", ConfigurationName="ldapService.ILdapServicePortType")]
    public interface ILdapServicePortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string getAttr2(string in0, string in1, string in2, string in3);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> getAttr2Async(string in0, string in1, string in2, string in3);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string verifySessionId(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> verifySessionIdAsync(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string verifySessionIdWithToken(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> verifySessionIdWithTokenAsync(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Nullable<bool> authUser3(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<System.Nullable<bool>> authUser3Async(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string authUser4(string in0, string in1, string in2, string in3);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> authUser4Async(string in0, string in1, string in2, string in3);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Nullable<bool> verifyUserName(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<System.Nullable<bool>> verifyUserNameAsync(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string verifySessionIdReturnAttr(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> verifySessionIdReturnAttrAsync(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string adminGetAttr(string in0, string in1, string in2, string in3, string in4);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> adminGetAttrAsync(string in0, string in1, string in2, string in3, string in4);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Nullable<bool> authUser(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<System.Nullable<bool>> authUserAsync(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        byte[] getFile();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<byte[]> getFileAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        void sessionRefresh(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task sessionRefreshAsync(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string Auth(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> AuthAsync(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string authUser2(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> authUser2Async(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string getAttr(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> getAttrAsync(string in0, string in1, string in2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ILdapServicePortTypeChannel : ldapService.ILdapServicePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class LdapServicePortTypeClient : System.ServiceModel.ClientBase<ldapService.ILdapServicePortType>, ldapService.ILdapServicePortType
    {
        
        /// <summary>
        /// 實作此部分方法來設定服務端點。
        /// </summary>
        /// <param name="serviceEndpoint">要設定的端點</param>
        /// <param name="clientCredentials">用戶端認證</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LdapServicePortTypeClient() : 
                base(LdapServicePortTypeClient.GetDefaultBinding(), LdapServicePortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ILdapServiceHttpPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LdapServicePortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(LdapServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), LdapServicePortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LdapServicePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LdapServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LdapServicePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LdapServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LdapServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string getAttr2(string in0, string in1, string in2, string in3)
        {
            return base.Channel.getAttr2(in0, in1, in2, in3);
        }
        
        public System.Threading.Tasks.Task<string> getAttr2Async(string in0, string in1, string in2, string in3)
        {
            return base.Channel.getAttr2Async(in0, in1, in2, in3);
        }
        
        public string verifySessionId(string in0)
        {
            return base.Channel.verifySessionId(in0);
        }
        
        public System.Threading.Tasks.Task<string> verifySessionIdAsync(string in0)
        {
            return base.Channel.verifySessionIdAsync(in0);
        }
        
        public string verifySessionIdWithToken(string in0, string in1)
        {
            return base.Channel.verifySessionIdWithToken(in0, in1);
        }
        
        public System.Threading.Tasks.Task<string> verifySessionIdWithTokenAsync(string in0, string in1)
        {
            return base.Channel.verifySessionIdWithTokenAsync(in0, in1);
        }
        
        public System.Nullable<bool> authUser3(string in0, string in1, string in2)
        {
            return base.Channel.authUser3(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<bool>> authUser3Async(string in0, string in1, string in2)
        {
            return base.Channel.authUser3Async(in0, in1, in2);
        }
        
        public string authUser4(string in0, string in1, string in2, string in3)
        {
            return base.Channel.authUser4(in0, in1, in2, in3);
        }
        
        public System.Threading.Tasks.Task<string> authUser4Async(string in0, string in1, string in2, string in3)
        {
            return base.Channel.authUser4Async(in0, in1, in2, in3);
        }
        
        public System.Nullable<bool> verifyUserName(string in0)
        {
            return base.Channel.verifyUserName(in0);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<bool>> verifyUserNameAsync(string in0)
        {
            return base.Channel.verifyUserNameAsync(in0);
        }
        
        public string verifySessionIdReturnAttr(string in0, string in1)
        {
            return base.Channel.verifySessionIdReturnAttr(in0, in1);
        }
        
        public System.Threading.Tasks.Task<string> verifySessionIdReturnAttrAsync(string in0, string in1)
        {
            return base.Channel.verifySessionIdReturnAttrAsync(in0, in1);
        }
        
        public string adminGetAttr(string in0, string in1, string in2, string in3, string in4)
        {
            return base.Channel.adminGetAttr(in0, in1, in2, in3, in4);
        }
        
        public System.Threading.Tasks.Task<string> adminGetAttrAsync(string in0, string in1, string in2, string in3, string in4)
        {
            return base.Channel.adminGetAttrAsync(in0, in1, in2, in3, in4);
        }
        
        public System.Nullable<bool> authUser(string in0, string in1)
        {
            return base.Channel.authUser(in0, in1);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<bool>> authUserAsync(string in0, string in1)
        {
            return base.Channel.authUserAsync(in0, in1);
        }
        
        public byte[] getFile()
        {
            return base.Channel.getFile();
        }
        
        public System.Threading.Tasks.Task<byte[]> getFileAsync()
        {
            return base.Channel.getFileAsync();
        }
        
        public void sessionRefresh(string in0)
        {
            base.Channel.sessionRefresh(in0);
        }
        
        public System.Threading.Tasks.Task sessionRefreshAsync(string in0)
        {
            return base.Channel.sessionRefreshAsync(in0);
        }
        
        public string Auth(string in0, string in1)
        {
            return base.Channel.Auth(in0, in1);
        }
        
        public System.Threading.Tasks.Task<string> AuthAsync(string in0, string in1)
        {
            return base.Channel.AuthAsync(in0, in1);
        }
        
        public string authUser2(string in0, string in1)
        {
            return base.Channel.authUser2(in0, in1);
        }
        
        public System.Threading.Tasks.Task<string> authUser2Async(string in0, string in1)
        {
            return base.Channel.authUser2Async(in0, in1);
        }
        
        public string getAttr(string in0, string in1, string in2)
        {
            return base.Channel.getAttr(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task<string> getAttrAsync(string in0, string in1, string in2)
        {
            return base.Channel.getAttrAsync(in0, in1, in2);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ILdapServiceHttpPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ILdapServiceHttpPort))
            {
                return new System.ServiceModel.EndpointAddress("http://tycgcloud.tycg.gov.tw/ldapService.do");
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return LdapServicePortTypeClient.GetBindingForEndpoint(EndpointConfiguration.ILdapServiceHttpPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return LdapServicePortTypeClient.GetEndpointAddress(EndpointConfiguration.ILdapServiceHttpPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ILdapServiceHttpPort,
        }
    }
}
