<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SDO.Base\SDO.Base.csproj" />
  </ItemGroup>

  <!--<ItemGroup>
    <ProjectReference Include="..\..\SDO\SDO.APP\SDO.APP.csproj" />
  </ItemGroup>-->

</Project>
