//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDO.i18N {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Label {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Label() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SDO.i18N.Label", typeof(Label).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 關卡簽核者 的當地語系化字串。
        /// </summary>
        public static string ActiveList_FLOW_AUDITOR {
            get {
                return ResourceManager.GetString("ActiveList_FLOW_AUDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 流程代碼 的當地語系化字串。
        /// </summary>
        public static string ActiveList_FLOW_CODE {
            get {
                return ResourceManager.GetString("ActiveList_FLOW_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 附件 的當地語系化字串。
        /// </summary>
        public static string Announcement_ATTACHMENT {
            get {
                return ResourceManager.GetString("Announcement_ATTACHMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公告事項 的當地語系化字串。
        /// </summary>
        public static string Announcement_COMMENT {
            get {
                return ResourceManager.GetString("Announcement_COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公告日期 的當地語系化字串。
        /// </summary>
        public static string Announcement_DATE {
            get {
                return ResourceManager.GetString("Announcement_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公告標題 的當地語系化字串。
        /// </summary>
        public static string Announcement_TITLE {
            get {
                return ResourceManager.GetString("Announcement_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 來高雄市觀光人數 的當地語系化字串。
        /// </summary>
        public static string Chart_CHART_TITLE {
            get {
                return ResourceManager.GetString("Chart_CHART_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 星期五 的當地語系化字串。
        /// </summary>
        public static string Chart_FRIDAY {
            get {
                return ResourceManager.GetString("Chart_FRIDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 當地人 的當地語系化字串。
        /// </summary>
        public static string Chart_LOCALS {
            get {
                return ResourceManager.GetString("Chart_LOCALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 星期一 的當地語系化字串。
        /// </summary>
        public static string Chart_MONDAY {
            get {
                return ResourceManager.GetString("Chart_MONDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 星期六 的當地語系化字串。
        /// </summary>
        public static string Chart_SATURDAY {
            get {
                return ResourceManager.GetString("Chart_SATURDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 星期日 的當地語系化字串。
        /// </summary>
        public static string Chart_SUNDAY {
            get {
                return ResourceManager.GetString("Chart_SUNDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 星期四 的當地語系化字串。
        /// </summary>
        public static string Chart_THURDAY {
            get {
                return ResourceManager.GetString("Chart_THURDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 星期二 的當地語系化字串。
        /// </summary>
        public static string Chart_TUESDAY {
            get {
                return ResourceManager.GetString("Chart_TUESDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 觀光客 的當地語系化字串。
        /// </summary>
        public static string Chart_VISITORS {
            get {
                return ResourceManager.GetString("Chart_VISITORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 星期三 的當地語系化字串。
        /// </summary>
        public static string Chart_WEDNESDAY {
            get {
                return ResourceManager.GetString("Chart_WEDNESDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能列表 的當地語系化字串。
        /// </summary>
        public static string DimRight_MAP_SetFunction {
            get {
                return ResourceManager.GetString("DimRight_MAP_SetFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 權限代碼 的當地語系化字串。
        /// </summary>
        public static string DimRight_RIGHT_ID {
            get {
                return ResourceManager.GetString("DimRight_RIGHT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 權限名稱 的當地語系化字串。
        /// </summary>
        public static string DimRight_RIGHT_NAME {
            get {
                return ResourceManager.GetString("DimRight_RIGHT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 權限列表 的當地語系化字串。
        /// </summary>
        public static string DimRole_MAP_DimRight {
            get {
                return ResourceManager.GetString("DimRole_MAP_DimRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色代碼 的當地語系化字串。
        /// </summary>
        public static string DimRole_ROLE_ID {
            get {
                return ResourceManager.GetString("DimRole_ROLE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色名稱 的當地語系化字串。
        /// </summary>
        public static string DimRole_ROLE_NAME {
            get {
                return ResourceManager.GetString("DimRole_ROLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 有效日期 的當地語系化字串。
        /// </summary>
        public static string eForm_EFFECTIVE_DATE {
            get {
                return ResourceManager.GetString("eForm_EFFECTIVE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 到期日期 的當地語系化字串。
        /// </summary>
        public static string eForm_EXPIRE_DATE {
            get {
                return ResourceManager.GetString("eForm_EXPIRE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 表單使用流程 的當地語系化字串。
        /// </summary>
        public static string eForm_FLOW_ID {
            get {
                return ResourceManager.GetString("eForm_FLOW_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 表單類型 的當地語系化字串。
        /// </summary>
        public static string eForm_FLOW_TYPE {
            get {
                return ResourceManager.GetString("eForm_FLOW_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 表單代碼 的當地語系化字串。
        /// </summary>
        public static string eForm_FORM_ID {
            get {
                return ResourceManager.GetString("eForm_FORM_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 表單名稱 的當地語系化字串。
        /// </summary>
        public static string eForm_FORM_NAME {
            get {
                return ResourceManager.GetString("eForm_FORM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        public static string eForm_MEMO {
            get {
                return ResourceManager.GetString("eForm_MEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 表單應用單位 的當地語系化字串。
        /// </summary>
        public static string eForm_ORG_ID {
            get {
                return ResourceManager.GetString("eForm_ORG_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 代理期間 的當地語系化字串。
        /// </summary>
        public static string EmpAgent_AGENT_DATE {
            get {
                return ResourceManager.GetString("EmpAgent_AGENT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 代理開始日期 的當地語系化字串。
        /// </summary>
        public static string EmpAgent_AGENT_FROM {
            get {
                return ResourceManager.GetString("EmpAgent_AGENT_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設定代理者帳號 的當地語系化字串。
        /// </summary>
        public static string EmpAgent_AGENT_ID {
            get {
                return ResourceManager.GetString("EmpAgent_AGENT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 代理帳號 的當地語系化字串。
        /// </summary>
        public static string EmpAgent_AGENT_NAME {
            get {
                return ResourceManager.GetString("EmpAgent_AGENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 代理結束日期 的當地語系化字串。
        /// </summary>
        public static string EmpAgent_AGENT_TO {
            get {
                return ResourceManager.GetString("EmpAgent_AGENT_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 組織代碼 的當地語系化字串。
        /// </summary>
        public static string EmpOrg_ORG_ID {
            get {
                return ResourceManager.GetString("EmpOrg_ORG_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 組織名稱 的當地語系化字串。
        /// </summary>
        public static string EmpOrg_ORG_NAME {
            get {
                return ResourceManager.GetString("EmpOrg_ORG_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上層組織 的當地語系化字串。
        /// </summary>
        public static string EmpOrg_PARENT_ID {
            get {
                return ResourceManager.GetString("EmpOrg_PARENT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色列表 的當地語系化字串。
        /// </summary>
        public static string EmpUser_MAP_DimRole {
            get {
                return ResourceManager.GetString("EmpUser_MAP_DimRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電子郵件 的當地語系化字串。
        /// </summary>
        public static string EmpUser_USER_EMAIL {
            get {
                return ResourceManager.GetString("EmpUser_USER_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者帳號 的當地語系化字串。
        /// </summary>
        public static string EmpUser_USER_ID {
            get {
                return ResourceManager.GetString("EmpUser_USER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者名稱 的當地語系化字串。
        /// </summary>
        public static string EmpUser_USER_NAME {
            get {
                return ResourceManager.GetString("EmpUser_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入密碼 的當地語系化字串。
        /// </summary>
        public static string EmpUser_USER_SECRET {
            get {
                return ResourceManager.GetString("EmpUser_USER_SECRET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 解密 的當地語系化字串。
        /// </summary>
        public static string EncryptDecrypt_DECRYPT {
            get {
                return ResourceManager.GetString("EncryptDecrypt_DECRYPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 解密錯誤 的當地語系化字串。
        /// </summary>
        public static string EncryptDecrypt_DECRYPT_ERROR {
            get {
                return ResourceManager.GetString("EncryptDecrypt_DECRYPT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 加密 的當地語系化字串。
        /// </summary>
        public static string EncryptDecrypt_ENCRYPT {
            get {
                return ResourceManager.GetString("EncryptDecrypt_ENCRYPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 加密失敗 的當地語系化字串。
        /// </summary>
        public static string EncryptDecrypt_ENCRYPT_ERROR {
            get {
                return ResourceManager.GetString("EncryptDecrypt_ENCRYPT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預設 的當地語系化字串。
        /// </summary>
        public static string EncryptDecrypt_INPUT_DEFAULT {
            get {
                return ResourceManager.GetString("EncryptDecrypt_INPUT_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 輸入字串不得為空 的當地語系化字串。
        /// </summary>
        public static string EncryptDecrypt_INPUT_NULL {
            get {
                return ResourceManager.GetString("EncryptDecrypt_INPUT_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 輸入字串 的當地語系化字串。
        /// </summary>
        public static string EncryptDecrypt_INPUT_SOURCE {
            get {
                return ResourceManager.GetString("EncryptDecrypt_INPUT_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 金鑰 的當地語系化字串。
        /// </summary>
        public static string EncryptDecrypt_KEY {
            get {
                return ResourceManager.GetString("EncryptDecrypt_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 輸出字串 的當地語系化字串。
        /// </summary>
        public static string EncryptDecrypt_OUTPUT_STR {
            get {
                return ResourceManager.GetString("EncryptDecrypt_OUTPUT_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者 的當地語系化字串。
        /// </summary>
        public static string FlowRole_MAP_USER {
            get {
                return ResourceManager.GetString("FlowRole_MAP_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色代碼 的當地語系化字串。
        /// </summary>
        public static string FlowRole_ROLE_ID {
            get {
                return ResourceManager.GetString("FlowRole_ROLE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色名稱 的當地語系化字串。
        /// </summary>
        public static string FlowRole_ROLE_NAME {
            get {
                return ResourceManager.GetString("FlowRole_ROLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號數 的當地語系化字串。
        /// </summary>
        public static string FlowRole_USER_COUNT {
            get {
                return ResourceManager.GetString("FlowRole_USER_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 有效日期 的當地語系化字串。
        /// </summary>
        public static string FlowSet_EFFECTIVE_DATE {
            get {
                return ResourceManager.GetString("FlowSet_EFFECTIVE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否啟用 的當地語系化字串。
        /// </summary>
        public static string FlowSet_ENABLE_FLG {
            get {
                return ResourceManager.GetString("FlowSet_ENABLE_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 到期日期 的當地語系化字串。
        /// </summary>
        public static string FlowSet_EXPIRE_DATE {
            get {
                return ResourceManager.GetString("FlowSet_EXPIRE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 流程代碼 的當地語系化字串。
        /// </summary>
        public static string FlowSet_FLOW_ID {
            get {
                return ResourceManager.GetString("FlowSet_FLOW_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 流程名稱 的當地語系化字串。
        /// </summary>
        public static string FlowSet_FLOW_NAME {
            get {
                return ResourceManager.GetString("FlowSet_FLOW_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 表單數 的當地語系化字串。
        /// </summary>
        public static string FlowSet_FORM_COUNT {
            get {
                return ResourceManager.GetString("FlowSet_FORM_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 流程說明 的當地語系化字串。
        /// </summary>
        public static string FlowSet_MEMO {
            get {
                return ResourceManager.GetString("FlowSet_MEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否決行 的當地語系化字串。
        /// </summary>
        public static string FlowSetDetail_SET_DECISION {
            get {
                return ResourceManager.GetString("FlowSetDetail_SET_DECISION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 流程 的當地語系化字串。
        /// </summary>
        public static string FlowSetDetail_SET_FLOW_ID {
            get {
                return ResourceManager.GetString("FlowSetDetail_SET_FLOW_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檢查憑證 的當地語系化字串。
        /// </summary>
        public static string FlowSetDetail_SET_OPTION_CERTIFICATE {
            get {
                return ResourceManager.GetString("FlowSetDetail_SET_OPTION_CERTIFICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MAIL 通知 的當地語系化字串。
        /// </summary>
        public static string FlowSetDetail_SET_OPTION_MAIL {
            get {
                return ResourceManager.GetString("FlowSetDetail_SET_OPTION_MAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否封存 的當地語系化字串。
        /// </summary>
        public static string FlowSetDetail_SET_OPTION_SEALED {
            get {
                return ResourceManager.GetString("FlowSetDetail_SET_OPTION_SEALED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否簽章 的當地語系化字串。
        /// </summary>
        public static string FlowSetDetail_SET_OPTION_SIGNATURE {
            get {
                return ResourceManager.GetString("FlowSetDetail_SET_OPTION_SIGNATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單位 的當地語系化字串。
        /// </summary>
        public static string FlowSetDetail_SET_ORG_ID {
            get {
                return ResourceManager.GetString("FlowSetDetail_SET_ORG_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色 的當地語系化字串。
        /// </summary>
        public static string FlowSetDetail_SET_ROLE_ID {
            get {
                return ResourceManager.GetString("FlowSetDetail_SET_ROLE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者 的當地語系化字串。
        /// </summary>
        public static string FlowSetDetail_SET_USER_ID {
            get {
                return ResourceManager.GetString("FlowSetDetail_SET_USER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 批核關卡 的當地語系化字串。
        /// </summary>
        public static string FlowSetDetail_STAGE {
            get {
                return ResourceManager.GetString("FlowSetDetail_STAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 關卡設定 的當地語系化字串。
        /// </summary>
        public static string FlowSetDetail_STAGE_SETTING {
            get {
                return ResourceManager.GetString("FlowSetDetail_STAGE_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 語言 的當地語系化字串。
        /// </summary>
        public static string Login_i18N {
            get {
                return ResourceManager.GetString("Login_i18N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入帳號 的當地語系化字串。
        /// </summary>
        public static string Login_LOGIN_ID {
            get {
                return ResourceManager.GetString("Login_LOGIN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入密碼 的當地語系化字串。
        /// </summary>
        public static string Login_LOGIN_SECRET {
            get {
                return ResourceManager.GetString("Login_LOGIN_SECRET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密件 的當地語系化字串。
        /// </summary>
        public static string MailLog_BCC_RECEIVER {
            get {
                return ResourceManager.GetString("MailLog_BCC_RECEIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 副本 的當地語系化字串。
        /// </summary>
        public static string MailLog_CC_RECEIVER {
            get {
                return ResourceManager.GetString("MailLog_CC_RECEIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寄送日期 的當地語系化字串。
        /// </summary>
        public static string MailLog_LOG_DATE {
            get {
                return ResourceManager.GetString("MailLog_LOG_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 收件者 的當地語系化字串。
        /// </summary>
        public static string MailLog_MAIL_RECEIVER {
            get {
                return ResourceManager.GetString("MailLog_MAIL_RECEIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寄件者 的當地語系化字串。
        /// </summary>
        public static string MailLog_MAIL_SENDER {
            get {
                return ResourceManager.GetString("MailLog_MAIL_SENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寄送狀態 的當地語系化字串。
        /// </summary>
        public static string MailLog_SEND_FLG {
            get {
                return ResourceManager.GetString("MailLog_SEND_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 建立日期 的當地語系化字串。
        /// </summary>
        public static string MailQueue_CRT_DATE {
            get {
                return ResourceManager.GetString("MailQueue_CRT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 郵件內容 的當地語系化字串。
        /// </summary>
        public static string MailQueue_MAIL_CONTENT {
            get {
                return ResourceManager.GetString("MailQueue_MAIL_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寄件者 的當地語系化字串。
        /// </summary>
        public static string MailQueue_MAIL_FROM {
            get {
                return ResourceManager.GetString("MailQueue_MAIL_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 郵件主旨 的當地語系化字串。
        /// </summary>
        public static string MailQueue_MAIL_SUBJECT {
            get {
                return ResourceManager.GetString("MailQueue_MAIL_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 收件者 的當地語系化字串。
        /// </summary>
        public static string MailQueue_MAIL_TO {
            get {
                return ResourceManager.GetString("MailQueue_MAIL_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寄出狀態 的當地語系化字串。
        /// </summary>
        public static string MailQueue_SEND_FLG {
            get {
                return ResourceManager.GetString("MailQueue_SEND_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寄件時間 的當地語系化字串。
        /// </summary>
        public static string MailQueue_SEND_TIME {
            get {
                return ResourceManager.GetString("MailQueue_SEND_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已送出 的當地語系化字串。
        /// </summary>
        public static string MailQueue_SENT {
            get {
                return ResourceManager.GetString("MailQueue_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 範本 的當地語系化字串。
        /// </summary>
        public static string MailQueue_TAB_TEMPLATE {
            get {
                return ResourceManager.GetString("MailQueue_TAB_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未送出 的當地語系化字串。
        /// </summary>
        public static string MailQueue_UNSEND {
            get {
                return ResourceManager.GetString("MailQueue_UNSEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者 的當地語系化字串。
        /// </summary>
        public static string MailRole_MAP_USER {
            get {
                return ResourceManager.GetString("MailRole_MAP_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色代碼 的當地語系化字串。
        /// </summary>
        public static string MailRole_ROLE_ID {
            get {
                return ResourceManager.GetString("MailRole_ROLE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色名稱 的當地語系化字串。
        /// </summary>
        public static string MailRole_ROLE_NAME {
            get {
                return ResourceManager.GetString("MailRole_ROLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號數 的當地語系化字串。
        /// </summary>
        public static string MailRole_USER_COUNT {
            get {
                return ResourceManager.GetString("MailRole_USER_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電子郵件 的當地語系化字串。
        /// </summary>
        public static string MailSet_EMAIL {
            get {
                return ResourceManager.GetString("MailSet_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電子郵件信箱 的當地語系化字串。
        /// </summary>
        public static string MailSet_MAIL_ADDRESS {
            get {
                return ResourceManager.GetString("MailSet_MAIL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 郵件內文 的當地語系化字串。
        /// </summary>
        public static string MailSet_MAIL_CONTENT {
            get {
                return ResourceManager.GetString("MailSet_MAIL_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 範本代碼 的當地語系化字串。
        /// </summary>
        public static string MailSet_MAIL_ID {
            get {
                return ResourceManager.GetString("MailSet_MAIL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 範本名稱 的當地語系化字串。
        /// </summary>
        public static string MailSet_MAIL_NAME {
            get {
                return ResourceManager.GetString("MailSet_MAIL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 郵件角色 的當地語系化字串。
        /// </summary>
        public static string MailSet_MAIL_ROLE {
            get {
                return ResourceManager.GetString("MailSet_MAIL_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 郵件主旨 的當地語系化字串。
        /// </summary>
        public static string MailSet_MAIL_SUBJECT {
            get {
                return ResourceManager.GetString("MailSet_MAIL_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 郵件抬頭 的當地語系化字串。
        /// </summary>
        public static string MailSet_MAIL_TITLE {
            get {
                return ResourceManager.GetString("MailSet_MAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寄、收件者 的當地語系化字串。
        /// </summary>
        public static string MailSet_TAB_MAIL_ADDRESS {
            get {
                return ResourceManager.GetString("MailSet_TAB_MAIL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 範本 的當地語系化字串。
        /// </summary>
        public static string MailSet_TAB_TEMPLATE {
            get {
                return ResourceManager.GetString("MailSet_TAB_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 對象 的當地語系化字串。
        /// </summary>
        public static string MailSet_TARGET {
            get {
                return ResourceManager.GetString("MailSet_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 郵寄類型 的當地語系化字串。
        /// </summary>
        public static string MailSet_TYPE {
            get {
                return ResourceManager.GetString("MailSet_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資源使用狀況 的當地語系化字串。
        /// </summary>
        public static string ResourceUsage_CHART_TITLE {
            get {
                return ResourceManager.GetString("ResourceUsage_CHART_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 分鐘 的當地語系化字串。
        /// </summary>
        public static string ResourceUsage_MINUTE {
            get {
                return ResourceManager.GetString("ResourceUsage_MINUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能代碼 的當地語系化字串。
        /// </summary>
        public static string SetFunction_FUNCTION_ID {
            get {
                return ResourceManager.GetString("SetFunction_FUNCTION_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能名稱 的當地語系化字串。
        /// </summary>
        public static string SetFunction_FUNCTION_NAME {
            get {
                return ResourceManager.GetString("SetFunction_FUNCTION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 網址 的當地語系化字串。
        /// </summary>
        public static string SetFunction_FUNCTION_URL {
            get {
                return ResourceManager.GetString("SetFunction_FUNCTION_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能類別 的當地語系化字串。
        /// </summary>
        public static string SetFunction_PARENT_ID {
            get {
                return ResourceManager.GetString("SetFunction_PARENT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序編號 的當地語系化字串。
        /// </summary>
        public static string SetFunction_SORT_ID {
            get {
                return ResourceManager.GetString("SetFunction_SORT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 參數說明 的當地語系化字串。
        /// </summary>
        public static string SetParam_MEMO {
            get {
                return ResourceManager.GetString("SetParam_MEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 參數類別 的當地語系化字串。
        /// </summary>
        public static string SetParam_SET_ITEM {
            get {
                return ResourceManager.GetString("SetParam_SET_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 參數代碼 的當地語系化字串。
        /// </summary>
        public static string SetParam_SET_TYPE {
            get {
                return ResourceManager.GetString("SetParam_SET_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 參數數值 的當地語系化字串。
        /// </summary>
        public static string SetParam_SET_VALUE {
            get {
                return ResourceManager.GetString("SetParam_SET_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 參數類別說明 的當地語系化字串。
        /// </summary>
        public static string SetParamItem_MEMO {
            get {
                return ResourceManager.GetString("SetParamItem_MEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 參數類別代碼 的當地語系化字串。
        /// </summary>
        public static string SetParamItem_SET_ITEM {
            get {
                return ResourceManager.GetString("SetParamItem_SET_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 參數類別 的當地語系化字串。
        /// </summary>
        public static string SetParamItem_SET_ITEM_NAME {
            get {
                return ResourceManager.GetString("SetParamItem_SET_ITEM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 日誌日期 的當地語系化字串。
        /// </summary>
        public static string SqlLog_LOG_DATE {
            get {
                return ResourceManager.GetString("SqlLog_LOG_DATE", resourceCulture);
            }
        }
    }
}
