//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDO.i18N {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SDO.i18N.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 登出系統，確定嗎？ 的當地語系化字串。
        /// </summary>
        public static string C01 {
            get {
                return ResourceManager.GetString("C01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 進行新增作業，確定嗎？ 的當地語系化字串。
        /// </summary>
        public static string C02 {
            get {
                return ResourceManager.GetString("C02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 進行修改作業，確定嗎？ 的當地語系化字串。
        /// </summary>
        public static string C03 {
            get {
                return ResourceManager.GetString("C03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 進行刪除作業，確定嗎？ 的當地語系化字串。
        /// </summary>
        public static string C04 {
            get {
                return ResourceManager.GetString("C04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 進行排序作業，確定嗎？ 的當地語系化字串。
        /// </summary>
        public static string C05 {
            get {
                return ResourceManager.GetString("C05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 送出流程作業，確定嗎？ 的當地語系化字串。
        /// </summary>
        public static string C06 {
            get {
                return ResourceManager.GetString("C06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 進行簽核作業，確定嗎？ 的當地語系化字串。
        /// </summary>
        public static string C07 {
            get {
                return ResourceManager.GetString("C07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 叡揚資訊股份有限公司 的當地語系化字串。
        /// </summary>
        public static string P01 {
            get {
                return ResourceManager.GetString("P01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SDO 框架展示 的當地語系化字串。
        /// </summary>
        public static string P02 {
            get {
                return ResourceManager.GetString("P02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統執行中，請稍後... 的當地語系化字串。
        /// </summary>
        public static string P03 {
            get {
                return ResourceManager.GetString("P03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統即將登出... 的當地語系化字串。
        /// </summary>
        public static string P04 {
            get {
                return ResourceManager.GetString("P04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳檔案限制10Mb 的當地語系化字串。
        /// </summary>
        public static string P05 {
            get {
                return ResourceManager.GetString("P05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統執行異常，請洽詢系統管理員 的當地語系化字串。
        /// </summary>
        public static string R01 {
            get {
                return ResourceManager.GetString("R01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者代號或是密碼輸入錯誤，請重新登入系統 的當地語系化字串。
        /// </summary>
        public static string R02 {
            get {
                return ResourceManager.GetString("R02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢無符合資料！ 的當地語系化字串。
        /// </summary>
        public static string R03 {
            get {
                return ResourceManager.GetString("R03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增作業成功！ 的當地語系化字串。
        /// </summary>
        public static string R04 {
            get {
                return ResourceManager.GetString("R04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改作業成功！ 的當地語系化字串。
        /// </summary>
        public static string R05 {
            get {
                return ResourceManager.GetString("R05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除作業成功！ 的當地語系化字串。
        /// </summary>
        public static string R06 {
            get {
                return ResourceManager.GetString("R06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0}已存在，新增作業失敗！ 的當地語系化字串。
        /// </summary>
        public static string R07 {
            get {
                return ResourceManager.GetString("R07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檔案上傳成功！ 的當地語系化字串。
        /// </summary>
        public static string R08 {
            get {
                return ResourceManager.GetString("R08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檔案不存在 的當地語系化字串。
        /// </summary>
        public static string R09 {
            get {
                return ResourceManager.GetString("R09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0}至{1}期間已有設定代理人！ 的當地語系化字串。
        /// </summary>
        public static string R10 {
            get {
                return ResourceManager.GetString("R10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用帳號數為零才能進行刪除作業 的當地語系化字串。
        /// </summary>
        public static string R11 {
            get {
                return ResourceManager.GetString("R11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇... 的當地語系化字串。
        /// </summary>
        public static string R12 {
            get {
                return ResourceManager.GetString("R12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} 欄位是必要項。 的當地語系化字串。
        /// </summary>
        public static string R13 {
            get {
                return ResourceManager.GetString("R13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} 已停用 的當地語系化字串。
        /// </summary>
        public static string R14 {
            get {
                return ResourceManager.GetString("R14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} 不是合法的郵件地址。 的當地語系化字串。
        /// </summary>
        public static string R15 {
            get {
                return ResourceManager.GetString("R15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 簽章驗證錯誤 的當地語系化字串。
        /// </summary>
        public static string R16 {
            get {
                return ResourceManager.GetString("R16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 非建立者，更新失敗 的當地語系化字串。
        /// </summary>
        public static string R17 {
            get {
                return ResourceManager.GetString("R17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新作業失敗！郵件已寄出 的當地語系化字串。
        /// </summary>
        public static string R18 {
            get {
                return ResourceManager.GetString("R18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除作業失敗！郵件已寄出 的當地語系化字串。
        /// </summary>
        public static string R19 {
            get {
                return ResourceManager.GetString("R19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者代號字元長度不得大於50或小於  的當地語系化字串。
        /// </summary>
        public static string S01 {
            get {
                return ResourceManager.GetString("S01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼長度不得小於  的當地語系化字串。
        /// </summary>
        public static string S02 {
            get {
                return ResourceManager.GetString("S02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼不得與使用者代號或名稱相同 的當地語系化字串。
        /// </summary>
        public static string S03 {
            get {
                return ResourceManager.GetString("S03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼不得含有特殊字元 的當地語系化字串。
        /// </summary>
        public static string S04 {
            get {
                return ResourceManager.GetString("S04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼所含特殊字元個數不得小於  的當地語系化字串。
        /// </summary>
        public static string S05 {
            get {
                return ResourceManager.GetString("S05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼必須為文數字組合 的當地語系化字串。
        /// </summary>
        public static string S06 {
            get {
                return ResourceManager.GetString("S06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼相鄰兩字元不得相同 的當地語系化字串。
        /// </summary>
        public static string S07 {
            get {
                return ResourceManager.GetString("S07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼相鄰三字元不可為連續升冪或降冪 的當地語系化字串。
        /// </summary>
        public static string S08 {
            get {
                return ResourceManager.GetString("S08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新密碼不得於過去  的當地語系化字串。
        /// </summary>
        public static string S09 {
            get {
                return ResourceManager.GetString("S09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 次重複 的當地語系化字串。
        /// </summary>
        public static string S10 {
            get {
                return ResourceManager.GetString("S10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 同一天連續輸入密碼錯誤超過 的當地語系化字串。
        /// </summary>
        public static string S11 {
            get {
                return ResourceManager.GetString("S11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 同一天非連續輸入密碼錯誤超過 的當地語系化字串。
        /// </summary>
        public static string S12 {
            get {
                return ResourceManager.GetString("S12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 次 的當地語系化字串。
        /// </summary>
        public static string S13 {
            get {
                return ResourceManager.GetString("S13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ，帳號鎖定 的當地語系化字串。
        /// </summary>
        public static string S14 {
            get {
                return ResourceManager.GetString("S14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 圖形驗證失敗，請更新驗證碼 的當地語系化字串。
        /// </summary>
        public static string S15 {
            get {
                return ResourceManager.GetString("S15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 註冊成功，請至電子郵件信箱收信! 的當地語系化字串。
        /// </summary>
        public static string S16 {
            get {
                return ResourceManager.GetString("S16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認證成功! 的當地語系化字串。
        /// </summary>
        public static string S17 {
            get {
                return ResourceManager.GetString("S17", resourceCulture);
            }
        }
    }
}
